### ISSUE TITLE
is the media category 'tweetvideo'?

### ISSUE THREAD

**Issue by javayoung** [twitterdev/large-video-upload-python#1]
I found the twitter document says media category should be tweet_video. 
But i looked into your code, it wrote as  'media_category': 'tweetvideo'
Does it work as well?
Thank you

**Comment by dk8996** [comment]
I noticed the same thing.
According to Twitter person in the community forum these are the valid values.

> Three possible values for media_category on the upload path at present:
> tweet_image
> tweet_gif (animated GIF only, static not supported)
> tweet_video
> These correspond to the three types of media described in the rest of the documentation. In due course I'll make sure to have this list added to the docs proper, but as I mentioned there may be a delay due to some ongoing additional work there.

[Media_category values](https://twittercommunity.com/t/media-category-values/64781/6)

**Comment by jcipriano** [comment]
Well, it appears they both work, but changed it to use tweet_video for consistency. Thanks for reporting.
