### ISSUE TITLE
how add this your method to twitter-python library ?

### ISSUE THREAD

**Issue by madu419** [twitterdev/large-video-upload-python#12]

**Comment by andypiper** [comment]
Can you provide more information about what you're trying to achieve here? This issue is not very clear as it stands.

**Comment by madu419** [comment]
ok. there is a library for the Twitter in python which has several method to upload video and images but to upload chunk video files there is **no** method, this problem i **solved** using your large-video-upload-python library

**Comment by andypiper** [comment]
OK cool, sounds like you might want to send a pull request to the library maintainer to improve the upload method in that code.

**Comment by madu419** [comment]
yes create pr for them but there is one method is there in that library to upload video as chunk, but that method has so many bugs and exception, for them it better to use your code its flawless

**Comment by andypiper** [comment]
Thanks for saying that, but this is not something that we are in a position to send to another project, this is why I closed your issue. Thanks!
