### ISSUE TITLE
Video upload always fails

### ISSUE THREAD

**Issue by marvic2409** [twitterdev/large-video-upload-python#14]
I get the error:
INIT
Media ID: 1263253181288546307
APPEND
986718 of 986718 bytes uploaded
Upload chunks complete.
FINALIZE
{'media_id': 1263253181288546307, 'media_id_string': '1263253181288546307', 'media_key': '7_1263253181288546307', 'size': 986718, 'expires_after_secs': 86400, 'processing_info': {'state': 'pending', 'check_after_secs': 1}}
Media processing status is pending 
Checking after 1 seconds
STATUS
Media processing status is failed 

I tried other videos and it does the same thing

**Comment by nandandutta** [comment]
INIT
Media ID: 1347896365569826817
APPEND
4194304 of 4891459 bytes uploaded
APPEND
4891459 of 4891459 bytes uploaded
Upload chunks complete.
FINALIZE
{'media_id': 1347896365569826817, 'media_id_string': '1347896365569826817', 'media_key': '7_1347896365569826817', 'size': 4891459, 'expires_after_secs': 86400, 'processing_info': {'state': 'pending', 'check_after_secs': 1}}
Media processing status is pending
Checking after 1 seconds
STATUS
Media processing status is failed

**Comment by nandandutta** [comment]
if you are getting this then you are on the right track .............
So after long research, we (Me & My GURU @Mr. Rohit Vinayak sir) came to know that the video format is not up to the mark as per Twitter...
we are sending MP4 with less duration but getting media processing status is failed. so what is the format?
ANS
Twitter currently supports the following video formats: MOV and MP4 formats for mobile apps. The minimum Twitter video length is 0.5 second and the maximum Twitter video length is 2 minutes 20 seconds (140 seconds) Twitter supports the following web video formats: MP4 video uploads with H264 format and AAC audio

Use mobile record video you will get your answer
